const express=require("express"),puppeteer=require("puppeteer"),axios=require("axios"),path=require("path"),http=require("http"),{Server}=require("socket.io"),app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||8e3;server.listen(PORT,()=>{console.log(`Server running on port ${PORT}`)}).on("error",err=>{"EADDRINUSE"===err.code?console.error(`Port ${PORT} is already in use. Please try a different port.`):console.error("Error starting server:",err),process.exit(1)}),app.set("view engine","ejs"),app.set("views",path.join(__dirname,"views")),app.use(express.static("public"));

app.use((req, res, next) => {
    res.setHeader("X-Frame-Options", "ALLOWALL");
    next();
});

async function getMetalPrices(){let e;try{e=await puppeteer.launch({headless:"new"});const t=await e.newPage();await t.goto("https://www.metalsdaily.com/live-prices/pgms/",{timeout:6e4});return await t.evaluate(()=>{const e={};return document.querySelectorAll("table tr").forEach(t=>{const r=t.querySelectorAll("td");if(r.length>2){let t=r[0].innerText.trim(),a=r[2].innerText.trim().replace(/,/g,"");t.includes("USD/OZ")&&(t=t.replace("USD/OZ","").trim(),e[t]=parseFloat(a)/28)}}),e})}catch(e){return console.error("Error scraping metal prices:",e.message),{Gold:0,Silver:0,Platinum:0,Palladium:0}}finally{e&&await e.close()}}async function getMetalData(e){const t=`https://query1.finance.yahoo.com/v8/finance/chart/${e}?range=3mo&interval=1d`;try{const e=await axios.get(t),r=e.data.chart.result[0];if(!r)throw new Error("No data returned from Yahoo Finance");return{dates:r.timestamp.map(e=>new Date(1e3*e).toISOString().split("T")[0]),prices:r.indicators.quote[0].close}}catch(e){return console.error("Error fetching data:",e),{dates:[],prices:[]}}}async function emitRealTimeUpdates(){try{const e=await getMetalPrices();io.emit("updatePrices",e)}catch(e){console.error("Error emitting real-time updates:",e.message)}}setInterval(emitRealTimeUpdates,1e4),app.get("/",(e,t)=>{t.send("Welcome to the Metal Prices API! Use /data to get the latest prices.")}),app.get("/data",async(e,t)=>{let r=await getMetalPrices(),a=await getMetalData("GC=F"),n=await getMetalData("SI=F"),o=await getMetalData("PL=F"),s=await getMetalData("PA=F");r.Gold=r.Gold||(a.prices.length>0?a.prices.slice(-1)[0]/28:0),r.Silver=r.Silver||(n.prices.length>0?n.prices.slice(-1)[0]/28:0),r.Platinum=r.Platinum||(o.prices.length>0?o.prices.slice(-1)[0]/28:0),r.Palladium=r.Palladium||(s.prices.length>0?s.prices.slice(-1)[0]/28:0),t.render("index",{metalPrices:r,goldData:a,silverData:n,platinumData:o,palladiumData:s})}),module.exports=app;

